# Generated by Django 5.0.6 on 2024-06-09 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance_indicator', '0002_remove_competenciesprofiency_performance_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='competenciesprofiency',
            name='performance_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='performance_indicator.performanceindicator'),
        ),
    ]
